name: Deploy to Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: jamduo/jamduo.github.io/.github/workflows/test_version.yml@main

  deploy:
    needs: build
    environment: Github.io
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - id: download_artifacts
        name: Download the static export
        with:
          name: static_content

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
