name: Deploy to Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  artifact-name: "static-export-staging"
  artifact-path: "./out/"
  concurrency: "production"

jobs:
  build:
    concurrency: ${{ env.concurrency }}
    uses: jamduo/jamduo.github.io/.github/workflows/build_test_export.yml@main
    with:
      node-version: "16.x"
      node-environment: "production"
      artifact-name: ${{ env.artifact-name }}
      artifact-path: ${{ env.artifact-path }}
      site-url: "https://jamduo.org"
    
  deploy:
    environment: Production

    needs: [ build ]
    concurrency: ${{ env.concurrency }}
    uses: jamduo/jamduo.github.io/.github/workflows/deploy_ssh.yml@main
    with:
      artifact-name: ${{ env.artifact-name }}
      artifact-path: ${{ env.artifact-path }}
    secrets:
      host: "${{ secrets.SSH_HOST }}"
      port: "${{ secrets.SSH_PORT }}"
      username: "${{ secrets.SSH_USER }}"
      rsa-key: "${{ secrets.SSH_RSA_KEY }}"
      target-path: "${{ secrets.PROJECT_PATH }}"
  
  deploy-github-pages:
    name: Deploy to Github Pages
    needs: build
    environment: Github.io
    concurrency: github_pages
    runs-on: ubuntu-latest

    steps:
      - id: download_artifacts
        name: Download the static export
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.artifact-path }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ${{ env.artifact-path }}
