name: Deploy to Production
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  artifact-name: "static-export-production"
  artifact-path: "./out/"
  deployment-target: "Production"

jobs:
  build:
    concurrency: $deployment-target

    uses: jamduo/jamduo.github.io/.github/workflows/build_test_export.yml@main
    with:
      deployment-target: $deployment-target
      node-version: "16.x"
      node-environment: "production"
      artifact-name: $artifact-name
      artifact-path: $artifact-path
      site-url: "https://staging.jamduo.org"
    
  deploy:
    needs: [ build ]
    concurrency: $deployment-target

    uses: jamduo/jamduo.github.io/.github/workflows/deploy.yml@main
    with:
      deployment-target: $deployment-target
      artifact-name: $artifact-name
      artifact-path: $artifact-path
    secrets:
      host: "${{ secrets.SSH_HOST }}"
      port: "${{ secrets.SSH_PORT }}"
      username: "${{ secrets.SSH_USER }}"
      rsa-key: "${{ secrets.SSH_RSA_KEY }}"
      target-path: "${{ secrets.PROJECT_PATH }}"
  
  deploy-github-pages:
    name: Deploy to Github Pages
    needs: build
    # environment: Github.io
    concurrency: github_pages
    runs-on: ubuntu-latest

    steps:
      - id: download_artifacts
        name: Download the static export
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.artifact-name }}
          path: ${{ env.artifact-path }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ${{ env.artifact-path }}
