name: Deploy to Staging
on:
  push:
    branches:
      - development
  workflow_dispatch:

env:
  artifact-name: "static-export-staging"
  artifact-path: "./out/"
  concurrency: "staging"

jobs:
  build:
    concurrency: ${{ env.concurrency }}
    uses: jamduo/jamduo.github.io/.github/workflows/build_test_export.yml@development
    with:
      node-version: "16.x"
      node-environment: "production"
      artifact-name: ${{ env.artifact-name }}
      artifact-path: ${{ env.artifact-path }}
      site-url: "https://staging.jamduo.org"
    
  deploy:
    environment: Staging

    needs: [ build ]
    concurrency: ${{ env.concurrency }}
    uses: jamduo/jamduo.github.io/.github/workflows/deploy_ssh.yml@development
    with:
      artifact-name: ${{ env.artifact-name }}
      artifact-path: ${{ env.artifact-path }}
    secrets:
      host: "${{ secrets.SSH_HOST }}"
      port: "${{ secrets.SSH_PORT }}"
      username: "${{ secrets.SSH_USER }}"
      rsa-key: "${{ secrets.SSH_RSA_KEY }}"
      target-path: "${{ secrets.STAGING_PROJECT_PATH }}"
